### ISSUE TITLE
Use AMISE bandwidth estimator 

### ISSUE THREAD

**Issue by FilomenoSanchez** [rigdenlab/conplot#133]
At the moment the bandwidth for the `sklearn.neighborsKernelDensity` calculation is being estimated using `sklearn.cluster.estimate_bandwidth`. Asymptotic Mean Integrated Squared Error (AMISE) algorithm should be used instead.

**Comment by FilomenoSanchez** [comment]
I'm tagging you here so that you know when this is implemented @DLMURPHY150

**Comment by darrencl** [comment]
@FilomenoSanchez Thank you for this! How can I access the `AMISE` for cross validating `sklearn.neighbors.KernelDensity`?

If I'm not mistaken, by looking at the closed PR, the AMISE is only available in the backend, i.e. `get_contact_density` function.

**Comment by FilomenoSanchez** [comment]
Hi @darrencl, the AMISE bandwidth estimation and all other kernel density related calculations are not accessible to users through conplot. This is because all calcualtions are done in the backend and conplot was never intended to be used as a python module that can be imported elsewhere. Instead, you could take a look at [conkit](https://github.com/rigdenlab/conkit), particularly at `conkit.misc.bandwidth`, which is what conplot uses to get the AMISE bandwidth. Conkit is a python package that can be installed using `pip install conkit`. Then you can just do `from conkit.misc.bandwidth import bandwidth_factory` and you should get access to all the bandwidth estimators implemented there (AMISE, Bowman, Scott...etc). Conkit was originally intended to work with evolutionary covariance data but in principle the functions implemented here should work with any kind of data as long as you pass it as a `np.array` of integers. Once you estimate the bandwidth then just pass it to `sklearn.neighbors.KernelDensity`. Here's a snippet of code that shows how we do this at conplot:
```python
    from conkit.misc.bandwidth import bandwidth_factory
    from sklearn.neighbors import KernelDensity

    bw = bandwidth_factory('amise')(x).bw
    kde = KernelDensity(bandwidth=bw).fit(x)
```
Where `x` is the data of interest. I hope this answers your question?
